export { default as General } from './General'
export { default as Tags } from './Tags'
export { default as Specialists } from './Specialists'
export { default as Synonyms } from './Synonyms'
export { default as Integrations } from './Integrations'
